---
version: "3.9"
services:
  api:
    #Uncomment "image" line instead of "build" line to get an image from cloud repository
    #image: artieartie/veri:latest
    build: .
    ports:
    - "8000:8000"
 